spring:
  config:
    activate:
      on-profile: "qa"

build:
  version: "2.0"

cards:
  message: "Welcome to MicroBank cards related local APIs "
  contactDetails:
    name: "Peggy Carter - QA Lead"
    email: "captiancarter@microbank.com"
  onCallSupport:
    - (555) 555-1234
    - (555) 523-1345