spring:
  config:
    activate:
      on-profile: "prod"

build:
  version: "1.0"

cards:
  message: "Welcome to MicroBank cards related local APIs "
  contactDetails:
    name: "Bruse Banner - Developer's LEad"
    email: "iamhulk@microbank.com"
  onCallSupport:
    - (555) 555-1234
    - (555) 523-1345