spring:
  config:
    activate:
      on-profile: "qa"

build:
  version: "2.0"

cards:
  message: "Welcome to MicroBank LOANS related local APIs: ENVIRONMENT : QA  "
  contactDetails:
    name: "Megan Fox - QA Lead"
    email: "whitetiger@microbank.com"
  onCallSupport:
    - (555) 555-1234
    - (555) 523-1345