server:
  port: 8090
spring:
  datasource:
    url: jdbc:h2:mem:testdb
    driverClassName: org.h2.Driver
    username: sa
    password: ''
  h2:
    console:
      enabled: true
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    hibernate:
      ddl-auto: update
    show-sql: true

build:
  verison: "3.0"

loan:
  message: "Welcome to MicroBank LOANS related local APIs: ENVIRONMENT: DEFAULT "
  contactDetails:
    name: "Peter Parker - Developer"
    email: "friendlyneighbourhood@microbank.com"
  onCallSupport:
    - (555) 555-1234
    - (555) 523-1345