spring:
  config:
    activate:
      on-profile: "prod"

build:
  version: "1.0"

cards:
  message: "Welcome to MicroBank cards related local APIs "
  contactDetails:
    name: "Tony Stark - Developer's Lead"
    email: "youknowme@microbank.com"
  onCallSupport:
    - (555) 555-1234
    - (555) 523-1345