spring:
  application:
    name: eurekaserver
  config:
    import: "optional:configserver:http://localhost:8071/"

# adding management utility for endpoints
management:
  endpoints:
    web:
      exposure:
        include: "*"
  # all the shit related to liveness and readiness
  health:
    readiness-state:
      enabled: true
    liveness-state:
      enabled: true
  endpoint:
    health:
      probes:
        enabled: true

logging:
  level:
    pattern:
      level: "%5p[${spring.application.name},%X{trace_id},%X{span_id}]"
