spring:
  config:
    activate:
      on-profile: "prod"

build:
  version: "1.0"


accounts:
  message: "Welcome to EazyBank accounts related local APIs "
  contactDetails:
    name: "Sachin Tripathi - Dev Lead"
    email: "iamtripathi@microbank.com"
  onCallSupport:
    - (555) 555-1234
    - (555) 523-1345