server:
  port: 8071

spring:
  application:
    name: "configserver"
  profiles:
    active: git
  cloud:
    config:
      server:
        native:
        # search-location: "classpath:/config"
        git:
          uri: https://github.com/sachintripathi0077/microbank_configs.git
          default-label: "main"
          timeout: 5
          clone-on-start: true
          force-pull: true
          username: sachintripathi0077
          password: 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

  # Connection details for rabbitmq
  rabbitmq:
    host: "localhost"
    port: 5672
    username: "guest"
    password: "guest"

# adding management utility for monitor endpoints
management:
  endpoints:
    web:
      exposure:
        include: "*"
  # all the shit related to liveness and readiness
  health:
    readiness-state:
      enabled: true
    liveness-state:
      enabled: true
  endpoint:
    health:
      probes:
        enabled: true